# Generated by Django 3.2.4 on 2021-06-17 09:15

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltInvestmentFundRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AltInvstmntFundData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fund_name', models.CharField(max_length=255)),
                ('fund_mngr_name', models.CharField(max_length=255)),
                ('fund_nature', models.CharField(choices=[('Impact Fund', 'Impact Fund'), ('Private Equity', 'Private Equity'), ('Venture Capital', 'Venture Capital')], max_length=20)),
                ('trustee_name', models.CharField(max_length=255)),
                ('fund_corpus', models.IntegerField()),
                ('reg_date', models.DateField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssetBackedSecuritiesLaws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AssetBackedSecuritiesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CloseFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('consent_date', models.DateField()),
                ('sub_open_date', models.DateField()),
                ('sub_close_date', models.DateField()),
                ('nbr_close_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DebentureList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DebtBondList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='DebtBondRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeTradedFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IpoBookbuildingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IpoFixedPriceCompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IpoFixedPriceRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IssueOfCapitalRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MutualFundRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OpenFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('consent_date', models.DateField()),
                ('sub_open_date', models.DateField()),
                ('sub_close_date', models.DateField()),
                ('initial_target', models.DecimalField(decimal_places=10, max_digits=19)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLimitedCompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PubIssueAppProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PublicLimitedCompanyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('document', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RightIssuesOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('approval_date', models.DateField()),
                ('sub_open_date', models.DateField()),
                ('sub_close_date', models.DateField()),
                ('record_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=10, max_digits=19)),
                ('abridged_ver', models.FileField(upload_to='uploads/')),
                ('full_ver', models.FileField(upload_to='uploads/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='RpoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor.fields.RichTextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('intactive', 'inactive')], default='active', max_length=10)),
            ],
        ),
    ]
